services:
  - type: web
    name: booking-gor
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node migrate.js && node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: booking-gor-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: QRIS_MERCHANT_ID
        value: GOR123456

databases:
  - name: booking-gor-db
    plan: free
    region: singapore # <-- Biar dekat dengan Indonesia dan jalannya cepat